### ISSUE TITLE
.ipynb does not exist on disc

### ISSUE THREAD

**Issue by td-anne** [notebookPowerTools/vscode-jupytext#23]
When I work on notebooks, there is often useful (slow to recompute) information in the outputs, so I prefer to have the `.ipynb` file around. But when I want to check things in to version control, I want to check the `.py` file. With this extension, the `.ipynb` file does not exist at all, so there is nowhere to store the output other than the editor's memory. If I close the editor (window) and then resume work later, all my outputs are gone.

In contrast, using JupyterLab plus jupytext, I can arrange to have both a `.ipynb` and ` .py` file around; when either is modified, the other is updated to match (effectively by running `jupytext --sync`). Thus one can comfortably modify either file and be sure that one's changes won't be lost, and the output persists locally but version control can restrict itself to the `.py` file.

**Comment by DonJayamanne** [comment]
Thanks for filing this issue, unfortunately thats not a feature I plan on supporting.
